CREATE TABLE MonthlyEnrollmentReporting (
    -- Maintain all table IDs for future updates
    ChildId uniqueidentifier,
    OrganizationId int,
    OrganizationName nvarchar(100),
    SiteId int,
    SiteName nvarchar(100),
    EnrollmentId int,
    FamilyDeterminationId int,
    FamilyId int,
    ReportingPeriodId int,
    ReportId int,
    Period varchar(25),
    ReportingPeriodStart date,
    ReportingPeriodEnd date,
    -- Used Variables
    Sasid nvarchar(max),
    LastName varchar(250),
    FirstName varchar(250),
    AgeGroupName varchar(50),
    TimeName varchar(5),
    SiteLicenseNumber int,
    RegionName varchar(50),
    TitleI bit,
    Entry date,
    [Exit] date,
    NumberOfPeople int,Income int,
    AmericanIndianOrAlaskaNative bit,
	Asian bit,
	BlackOrAfricanAmerican bit,
	NativeHawaiianOrPacificIslander bit,
	White bit,
	TwoOrMoreRaces bit,
	HispanicOrLatinxEthnicity bit,
	Gender int,
    Foster bit,
    Accredited bit,
    Rate decimal (18,2),
    CDCRevenue decimal (18,2),
    FundingSource int,
    SMI75 int,
    FPL200 int,
    Under75SMI bit,
    Under200FPL bit,
    ActiveC4K bit,
    CONSTRAINT MonthlyEnrollment UNIQUE
    (ChildId,
    EnrollmentId,
    ReportingPeriodId,
    ReportId,
    FundingSource)
);