# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pr:
  branches:
    include:
    - '*'

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: test_ece_extraction
  displayName: 'ECE Extraction'

  steps:
    - task: UsePythonVersion@0
      inputs:
       versionSpec: '3.6'
    - script: pip install -r requirements.txt
      displayName: 'Install requirements'

    - task: DockerCompose@0
      displayName: "Run Docker Compose"
      inputs:
       dockerComposeFile: "docker-compose.yml"
       dockerComposeCommand: "up --exit-code-from test_backend"

    - script: |
        pip install pytest
        pip install pytest-cov
        pytest tests --doctest-modules --junitxml=junit/test-results.xml --cov=. --cov-report=xml --cov-report=html
      displayName: 'Test with pytest'

    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        testResultsFiles: '**/test-*.xml'
        testRunTitle: 'Publish test results for Python $(python.version)'


