# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pr:
  branches:
    include:
    - '*'

pool:
  vmImage: 'ubuntu-latest'

- job: test_ece_extraction
  displayName: 'ECE Extraction'

  steps:
    - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.6'
    - script: pip install -r requirements.txt
      displayName: 'Install requirements'
    - script: echo Hello, world!
      displayName: 'Run a one-line script'

    - task: PythonScript@0
      inputs:
        scriptSource: 'inline'
        script: |
          print('Hello world 1')
          print('Hello world 2')
