version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./tests:/tests
      - ./src:/src
      - ./run.sh:/run.sh
      - ./tests/config.ini:/src/resource_access/config.ini
    entrypoint:
      - /bin/bash
      - run.sh
    depends_on:
      - test_db
  test_db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: TestPassword1
      ACCEPT_EULA: Y
    logging:
      driver: "none"
