ECIS_SUMMER_2020 = 'data/ecis_july_data.csv'
# This file is a tab separated cut and paste from the password protected file provided by Julie Bisi
ALL_SITE_FILE = 'data/all_sites.csv'

COLUMN_MAPPING_ECIS_ECE = {
    'FirstName': 'First Name',
    'MiddleName': 'Middle Name',
    'LastName': 'Last Name',
    'Suffix': 'Suffix',
    'DateOfBirth': 'Date of birth',
    # '': 'Birth certificate type',
    'BirthCertificateId': 'Birth certificate ID #',
    'TownOfBirth': 'Town of birth',
    'StateOfBirth': 'State of birth',
    'AmericanIndianOrAlaskaNative': 'Race: American Indian or Alaska Native',
    'Asian': 'Race: Asian',
    'BlackOrAfricanAmerican': 'Race: Black or African American',
    'NativeHawaiianOrOtherPacificIslander': 'Race: Native Hawaiian or Pacific Islander',
    'White': 'Race: white',
    # '': 'Race not disclosed',
    'Ethnicity': 'Hispanic or Latinx ethnicity',
    'Gender': 'Gender',
    # '': 'Dual language learner',
    'IEP': 'Receiving disability and/or special education services',
    # '': 'Street address',
    'Town': 'Town',
    'State': 'State',
    'ZipCode': 'Zipcode',
    # '': 'Lives with foster family',
    # '': 'Experiencing homelessness or housing insecurity',
    'NumberOfPeopleInHousehold': 'Household size',
    'AnnualFamilyIncome': 'Annual household income',
    'DateFamilyIncomeDocumented': 'Determination date',
    # '': 'Provider',
    # '': 'Site',
    # '': 'Care model',
    # '': 'Age group',
    # '': 'Enrollment start date',
    # '': 'Enrollment end date',
    # '': 'Enrollment exit reason',
    'FundingType': 'Funding type',
    'SpaceType': 'Space type',
    # '': 'First funding period',
    # '': 'Last funding period',
}