ECIS_SUMMER_2020 = 'data/ecis_july_data.csv'
# This file is a tab separated cut and paste from the password protected file provided by Julie Bisi
ALL_SITE_FILE = 'data/all_sites.csv'

RACE_COLS = ['Race: American Indian or Alaska Native',
             'Race: Asian',
             'Race: Black or African American',
             'Race: Native Hawaiian or Pacific Islander',
             'Race: white']

ECE_COLUMNS = ['First name',
               'Middle name',
               'Last name',
               'Suffix',
               'SASID / unique identifier',
               'Date of birth',
               'Birth certificate type',
               'Birth certificate ID #',
               'Town of birth',
               'State of birth',
               'Race not disclosed',
               'Hispanic or Latinx ethnicity',
               'Gender',
               'Dual language learner',
               'Receiving disability and/or special education services',
               'Street address',
               'Town',
               'State',
               'Zipcode',
               'Lives with foster family',
               'Experiencing homelessness or housing insecurity',
               'Household size',
               'Annual household income',
               'Determination date',
               'Provider',
               'Site',
               'Care model',
               'Age group',
               'Enrollment start date',
               'Enrollment end date',
               'Enrollment exit reason',
               'Funding type',
               'Space type',
               'First funding period',
               'Last funding period'] + RACE_COLS

COLUMN_MAPPING_ECIS_ECE = {
    'FirstName': 'First Name',
    'MiddleName': 'Middle Name',
    'LastName': 'Last Name',
    'Suffix': 'Suffix',
    'SASID': 'SASID / unique identifier',
    'DateOfBirth': 'Date of birth',
    'BirthCertificateId': 'Birth certificate ID #',
    'TownOfBirth': 'Town of birth',
    'StateOfBirth': 'State of birth',
    'AmericanIndianOrAlaskaNative': 'Race: American Indian or Alaska Native',
    'Asian': 'Race: Asian',
    'BlackOrAfricanAmerican': 'Race: Black or African American',
    'NativeHawaiianOrOtherPacificIslander': 'Race: Native Hawaiian or Pacific Islander',
    'White': 'Race: white',
    'Ethnicity': 'Hispanic or Latinx ethnicity',
    'Gender': 'Gender',
    'IEP': 'Receiving disability and/or special education services',
    'Town': 'Town',
    'State': 'State',
    'ZipCode': 'Zipcode',
    'NumberOfPeopleInHousehold': 'Household size',
    'AnnualFamilyIncome': 'Annual household income',
    'DateFamilyIncomeDocumented': 'Determination date',
    # '': 'Provider',
    # '': 'Site',
    # '': 'Age group',
    'FacilityEntryDate': 'Enrollment start date',
    'FacilityExitDate': 'Enrollment end date',
    'ExitCategory': 'Enrollment exit reason',
    'FundingType': 'Funding type',
    'SpaceType': 'Space type',
    'FundingStartDate': 'First funding period',
    'FundingEndDate': 'Last funding period'
}

EXIT_REASONS = {'Aged Out':'Aged out',
                'Child Stopped Attending':'Stopped attending',
                'Chose to Attend A Different Program':'Chose to attend a different program',
                'Moved to Another Town':'Moved within Connecticut',
                'Moved to Another State':'Moved to another state',
                'Child Was Asked To Leave':'Child was asked to leave',
                'Other':'Unknown',
                'Parent Withdrew Child':'Stopped attending',
                'Unknown':'Unknown'}